### ISSUE TITLE
Superfluous code in SPA

### ISSUE THREAD

**Issue by Razpudding** [eltongonc/web_app_from_scratch#8]
https://github.com/eltongonc/web_app_from_scratch/blob/master/opdracht5-spa/assets/js/app.js#L24

A switch case might be more useful if you're working with a lot of possible values of one variable.
Also, consider using:
var myvariable =
instead of
var myVariable;
myVariable =

**Comment by eltongonc** [comment]
I cleaned up, updated and added comments to the coded.
