### ISSUE TITLE
Nice element creation pattern

### ISSUE THREAD

**Issue by Razpudding** [eltongonc/web_app_from_scratch#9]
I don't know if this is a standard way of generating HTML but it looks pretty cool.
Try to cut down on your whitespace though, there's waaay too many linebreaks.

Also, if you agree to use forEach in one instance, why not use it everywhere for consistency?

**Comment by eltongonc** [comment]
I was messing around with js Classes and ended up with this. I believe this is close to what react does. The linebreaks helps me navigate through my code. I stepped out of my comfort-zone with the forEach function. I need to get used to. According to Dave Bitter the foreEach function is less code, but it make me think more.
